name: flutter_structure_v2024
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  bloc_test: ^9.1.7
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  freezed: ^2.5.2
  get_it: ^7.7.0
  go_router: ^14.2.6
  json_annotation: ^4.9.0
  logger: ^2.4.0
  mockito: ^5.4.4
  mocktail: ^1.0.4
  retrofit: ^4.2.0
  retrofit_generator: ^8.2.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true
